# TCL File Generated by Component Editor 17.1
# Wed May 20 12:11:20 CEST 2020
# DO NOT MODIFY


# 
# Tone_generation "Tone_generation" v1.1
#  2020.05.20.12:11:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Tone_generation
# 
set_module_property DESCRIPTION ""
set_module_property NAME Tone_generation
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Tone_generation
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Tone_generation_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Tone_generation_top.vhd VHDL PATH IP/Tone_generation/Tone_generation_top.vhd TOP_LEVEL_FILE
add_fileset_file cic_codec.vhd VHDL PATH IP/Tone_generation/cic_codec.vhd
add_fileset_file cordic_control.vhd VHDL PATH IP/Tone_generation/cordic_control.vhd
add_fileset_file cordic_pipelined.vhd VHDL PATH IP/Tone_generation/cordic_pipelined.vhd
add_fileset_file freq_mes.vhd VHDL PATH IP/Tone_generation/freq_mes.vhd
add_fileset_file mixer.vhd VHDL PATH IP/Tone_generation/mixer.vhd


# 
# parameters
# 
add_parameter dat_len_avl NATURAL 31
set_parameter_property dat_len_avl DEFAULT_VALUE 31
set_parameter_property dat_len_avl DISPLAY_NAME dat_len_avl
set_parameter_property dat_len_avl TYPE NATURAL
set_parameter_property dat_len_avl UNITS None
set_parameter_property dat_len_avl ALLOWED_RANGES 0:2147483647
set_parameter_property dat_len_avl HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_square_freq export Input 1


# 
# connection point ser
# 
add_interface ser avalon_streaming start
set_interface_property ser associatedClock clock
set_interface_property ser associatedReset reset
set_interface_property ser dataBitsPerSymbol 24
set_interface_property ser errorDescriptor ""
set_interface_property ser firstSymbolInHighOrderBits true
set_interface_property ser maxChannel 0
set_interface_property ser readyLatency 0
set_interface_property ser ENABLED true
set_interface_property ser EXPORT_OF ""
set_interface_property ser PORT_NAME_MAP ""
set_interface_property ser CMSIS_SVD_VARIABLES ""
set_interface_property ser SVD_ADDRESS_GROUP ""

add_interface_port ser aso_seR_ready ready Input 1
add_interface_port ser aso_seR_valid valid Output 1
add_interface_port ser aso_seR_data data Output 24


# 
# connection point sel
# 
add_interface sel avalon_streaming start
set_interface_property sel associatedClock clock
set_interface_property sel associatedReset reset
set_interface_property sel dataBitsPerSymbol 24
set_interface_property sel errorDescriptor ""
set_interface_property sel firstSymbolInHighOrderBits true
set_interface_property sel maxChannel 0
set_interface_property sel readyLatency 0
set_interface_property sel ENABLED true
set_interface_property sel EXPORT_OF ""
set_interface_property sel PORT_NAME_MAP ""
set_interface_property sel CMSIS_SVD_VARIABLES ""
set_interface_property sel SVD_ADDRESS_GROUP ""

add_interface_port sel aso_seL_ready ready Input 1
add_interface_port sel aso_seL_valid valid Output 1
add_interface_port sel aso_seL_data data Output 24


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end coe_DACLRC export Input 1


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock clock
set_interface_property conduit_end_1 associatedReset ""
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 coe_freq_up_down export Bidir 2

