# TCL File Generated by Component Editor 17.1
# Fri Jul 24 15:29:24 CEST 2020
# DO NOT MODIFY


# 
# volume_generation_top "volume_generation_top" v1.0
#  2020.07.24.15:29:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module volume_generation_top
# 
set_module_property DESCRIPTION ""
set_module_property NAME volume_generation_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME volume_generation_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Volume_generation_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Volume_generation_top.vhd VHDL PATH ../vhdl/Volume_generation/Volume_generation_top.vhd TOP_LEVEL_FILE
add_fileset_file cordic_control.vhd VHDL PATH ../vhdl/Volume_generation/cordic/cordic_control.vhd
add_fileset_file cordic_pipelined.vhd VHDL PATH ../vhdl/Volume_generation/cordic/cordic_pipelined.vhd
add_fileset_file Filter.vhd VHDL PATH ../vhdl/Volume_generation/filter/Filter.vhd
add_fileset_file cic.vhd VHDL PATH ../vhdl/Volume_generation/filter/cic.vhd
add_fileset_file CalGlis.vhd VHDL PATH ../vhdl/Volume_generation/freq_mes/Cal_Glis/CalGlis.vhd
add_fileset_file goldschmidt.vhd VHDL PATH ../vhdl/Volume_generation/freq_mes/Goldschmidt/goldschmidt.vhd
add_fileset_file FIR.vhd VHDL PATH ../vhdl/Volume_generation/freq_mes/FIR.vhd
add_fileset_file count_freq_meas.vhd VHDL PATH ../vhdl/Volume_generation/freq_mes/count_freq_meas.vhd
add_fileset_file freq_meas.vhd VHDL PATH ../vhdl/Volume_generation/freq_mes/freq_meas.vhd
add_fileset_file mixer.vhd VHDL PATH ../vhdl/Volume_generation/mixer/mixer.vhd


# 
# parameters
# 
add_parameter dat_len_avl NATURAL 32
set_parameter_property dat_len_avl DEFAULT_VALUE 32
set_parameter_property dat_len_avl DISPLAY_NAME dat_len_avl
set_parameter_property dat_len_avl TYPE NATURAL
set_parameter_property dat_len_avl UNITS None
set_parameter_property dat_len_avl ALLOWED_RANGES 0:2147483647
set_parameter_property dat_len_avl HDL_PARAMETER true
add_parameter cic1Bits NATURAL 21
set_parameter_property cic1Bits DEFAULT_VALUE 21
set_parameter_property cic1Bits DISPLAY_NAME cic1Bits
set_parameter_property cic1Bits TYPE NATURAL
set_parameter_property cic1Bits UNITS None
set_parameter_property cic1Bits ALLOWED_RANGES 0:2147483647
set_parameter_property cic1Bits HDL_PARAMETER true
add_parameter cic2Bits NATURAL 25
set_parameter_property cic2Bits DEFAULT_VALUE 25
set_parameter_property cic2Bits DISPLAY_NAME cic2Bits
set_parameter_property cic2Bits TYPE NATURAL
set_parameter_property cic2Bits UNITS None
set_parameter_property cic2Bits ALLOWED_RANGES 0:2147483647
set_parameter_property cic2Bits HDL_PARAMETER true
add_parameter cic3Bits NATURAL 28
set_parameter_property cic3Bits DEFAULT_VALUE 28
set_parameter_property cic3Bits DISPLAY_NAME cic3Bits
set_parameter_property cic3Bits TYPE NATURAL
set_parameter_property cic3Bits UNITS None
set_parameter_property cic3Bits ALLOWED_RANGES 0:2147483647
set_parameter_property cic3Bits HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point svg
# 
add_interface svg avalon end
set_interface_property svg addressUnits WORDS
set_interface_property svg associatedClock clock
set_interface_property svg associatedReset reset
set_interface_property svg bitsPerSymbol 8
set_interface_property svg burstOnBurstBoundariesOnly false
set_interface_property svg burstcountUnits WORDS
set_interface_property svg explicitAddressSpan 0
set_interface_property svg holdTime 0
set_interface_property svg linewrapBursts false
set_interface_property svg maximumPendingReadTransactions 0
set_interface_property svg maximumPendingWriteTransactions 0
set_interface_property svg readLatency 0
set_interface_property svg readWaitTime 1
set_interface_property svg setupTime 0
set_interface_property svg timingUnits Cycles
set_interface_property svg writeWaitTime 0
set_interface_property svg ENABLED true
set_interface_property svg EXPORT_OF ""
set_interface_property svg PORT_NAME_MAP ""
set_interface_property svg CMSIS_SVD_VARIABLES ""
set_interface_property svg SVD_ADDRESS_GROUP ""

add_interface_port svg avs_sVG_write write Input 1
add_interface_port svg avs_sVG_address address Input 2
add_interface_port svg avs_sVG_writedata writedata Input dat_len_avl
add_interface_port svg avs_sVG_readdata readdata Output dat_len_avl
set_interface_assignment svg embeddedsw.configuration.isFlash 0
set_interface_assignment svg embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment svg embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment svg embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset reset
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_square_freq export Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end coe_freq_up_down export Input 2

