# TCL File Generated by Component Editor 17.1
# Wed Jul 29 12:11:59 CEST 2020
# DO NOT MODIFY


# 
# audio_serializer "audio_serializer" v1.0
#  2020.07.29.12:11:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module audio_serializer
# 
set_module_property DESCRIPTION ""
set_module_property NAME audio_serializer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP digital_theremin
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME audio_serializer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL audio_serializer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file audio_serializer.vhd VHDL PATH ../vhdl/audio_serializer/audio_serializer.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset reset
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_AUD1_BCLK coe_aud1_bclk Input 1
add_interface_port conduit_end_0 coe_AUD2_DACDAT coe_aud2_dacdat Output 1
add_interface_port conduit_end_0 coe_AUD3_DACLRCK coe_aud3_daclrck Input 1


# 
# connection point se
# 
add_interface se avalon_streaming end
set_interface_property se associatedClock clock
set_interface_property se associatedReset reset
set_interface_property se dataBitsPerSymbol 24
set_interface_property se errorDescriptor ""
set_interface_property se firstSymbolInHighOrderBits true
set_interface_property se maxChannel 0
set_interface_property se readyLatency 0
set_interface_property se ENABLED true
set_interface_property se EXPORT_OF ""
set_interface_property se PORT_NAME_MAP ""
set_interface_property se CMSIS_SVD_VARIABLES ""
set_interface_property se SVD_ADDRESS_GROUP ""

add_interface_port se asi_se_ready ready Output 1
add_interface_port se asi_se_valid valid Input 1
add_interface_port se asi_se_data data Input 24

