# TCL File Generated by Component Editor 17.1
# Fri May 15 13:34:09 CEST 2020
# DO NOT MODIFY


# 
# Test1kHzSineComponent "Test1kHzSineComponent" v1.0
#  2020.05.15.13:34:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Test1kHzSineComponent
# 
set_module_property DESCRIPTION ""
set_module_property NAME Test1kHzSineComponent
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Test1kHzSineComponent
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sine1kHz
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sine_1kHz.vhd VHDL PATH IP/Tone_generation/sine_1kHz.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter count_freq INTEGER 48
set_parameter_property count_freq DEFAULT_VALUE 48
set_parameter_property count_freq DISPLAY_NAME count_freq
set_parameter_property count_freq TYPE INTEGER
set_parameter_property count_freq UNITS None
set_parameter_property count_freq HDL_PARAMETER true
add_parameter count_samp INTEGER 256
set_parameter_property count_samp DEFAULT_VALUE 256
set_parameter_property count_samp DISPLAY_NAME count_samp
set_parameter_property count_samp TYPE INTEGER
set_parameter_property count_samp UNITS None
set_parameter_property count_samp HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point sel
# 
add_interface sel avalon_streaming start
set_interface_property sel associatedClock clock
set_interface_property sel associatedReset reset
set_interface_property sel dataBitsPerSymbol 8
set_interface_property sel errorDescriptor ""
set_interface_property sel firstSymbolInHighOrderBits true
set_interface_property sel maxChannel 0
set_interface_property sel readyLatency 0
set_interface_property sel ENABLED true
set_interface_property sel EXPORT_OF ""
set_interface_property sel PORT_NAME_MAP ""
set_interface_property sel CMSIS_SVD_VARIABLES ""
set_interface_property sel SVD_ADDRESS_GROUP ""

add_interface_port sel aso_seL_ready ready Input 1
add_interface_port sel aso_seL_valid valid Output 1
add_interface_port sel aso_seL_data data Output 24


# 
# connection point ser
# 
add_interface ser avalon_streaming start
set_interface_property ser associatedClock clock
set_interface_property ser associatedReset reset
set_interface_property ser dataBitsPerSymbol 8
set_interface_property ser errorDescriptor ""
set_interface_property ser firstSymbolInHighOrderBits true
set_interface_property ser maxChannel 0
set_interface_property ser readyLatency 0
set_interface_property ser ENABLED true
set_interface_property ser EXPORT_OF ""
set_interface_property ser PORT_NAME_MAP ""
set_interface_property ser CMSIS_SVD_VARIABLES ""
set_interface_property ser SVD_ADDRESS_GROUP ""

add_interface_port ser aso_seR_ready ready Input 1
add_interface_port ser aso_seR_valid valid Output 1
add_interface_port ser aso_seR_data data Output 24

